name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Composer (php-actions)
        uses: php-actions/composer@v6
      - name: PHP Static Analysis
        uses: php-actions/composer@v6
        with:
          command: phpstan
      - name: PHP Check style
        uses: php-actions/composer@v6
        with:
          command: phpcs
      - name: PHP Mess detector
        uses: php-actions/composer@v6
        with:
          command: phpmd
      - name: PHP Unit tests
        uses: php-actions/composer@v6
        with:
          command: phpunit
